#! /usr/bin/env sh

# First test skipped for now stdin

failed=0
total=13

[ "$1" = "-v" ] && verbose=1

test_f()
{
	test="$(diff tmp ./cases/$1)"
	[ -n "$test" ] && echo "Test #$1 failed" && ((failed=failed+1))
	[ -n "$test" ] && [ $verbose ] && echo "$test"
	rm tmp
}

cat stock-2.log | head -n 5 | ./tradelog > tmp
test_f 1

./tradelog -t TSLA -t V stock-2.log > tmp
test_f 2

./tradelog -t CVX stock-4.log.gz | head -n 3 > tmp
test_f 3

./tradelog list-tick stock-2.log > tmp
test_f 4

./tradelog profit stock-2.log > tmp
test_f 5

./tradelog -t TSM -t PYPL stock-2.log  profit> tmp
test_f 6

./tradelog pos stock-2.log > tmp
test_f 7

./tradelog -t TSM -t PYPL -t AAPL pos stock-2.log > tmp
test_f 8

./tradelog last-price stock-2.log > tmp
test_f 9

./tradelog hist-ord stock-2.log > tmp
test_f 10

./tradelog -w 100 graph-pos stock-6.log > tmp
test_f 11

./tradelog -w 10 -t FB -t JNJ -t WMT graph-pos stock-6.log > tmp
test_f 12

cat /dev/null | ./tradelog profit > tmp
test_f 13

echo "$((total-failed))/$total tests succeeded"
