#! /usr/bin/env sh

# First test skipped for now stdin

failed=0
total=8

[ "$1" = "-v" ] && verbose=1

test_f()
{
	test="$(diff tmp ./cases/$1)"
	[ -n "$test" ] && echo "Test #$1 failed" && ((failed=failed+1))
	[ -n "$test" ] && [ $verbose ] && echo "$test"
	rm tmp
}

./tradelog -t TSLA -t V stock-2.log > tmp
test_f 2

# Skip third for now .gz

./tradelog list-tick stock-2.log > tmp
test_f 4

./tradelog profit stock-2.log > tmp
test_f 5

./tradelog profit -t TSM -t PYPL stock-2.log > tmp
test_f 6

./tradelog pos stock-2.log > tmp
test_f 7

./tradelog pos -t TSM -t PYPL -t AAPL stock-2.log > tmp
test_f 8

echo "$((total-failed))/$total tests succeeded"
